css-positioning -Scarlet Kim
Scarlet-K/c0522-code-solutions pull request #19
Opened 2022-05-13 18:23 UTC by Scarlet-K

![relative](https://user-images.githubusercontent.com/103100017/168344415-184eb8f3-a4df-42b0-a07e-0cfc02466b6e.png)
![absolute](https://user-images.githubusercontent.com/103100017/168344422-51f2d604-2ae5-4571-bab4-d733de5cfaf4.png)
![fixed](https://user-images.githubusercontent.com/103100017/168344423-b04b563a-5ad0-4e5a-a9da-62faff78e7fb.gif)

2022-05-14 23:32 UTC, codingcodymiller requested changes

2022-05-14 23:32 UTC, codingcodymiller commented on css-positioning/fixed.css
> +  right: calc(100% / 3);
If you make the title `width: 100%`, this won't be necessary, since `text-align: center;` has already been applied

2022-05-16 17:00 UTC, Scarlet-K commented
![Fixed fixed](https://user-images.githubusercontent.com/103100017/168645138-ca95e199-4cbf-4477-9606-35c3024b22d8.png)

2022-05-16 22:17 UTC, codingcodymiller approved these changes

2022-05-16 22:41 UTC, merged