Object manipulation 1 - Scarlet Kim
Scarlet-K/c0522-code-solutions pull request #52
Opened 2022-05-28 04:13 UTC by Scarlet-K

2022-05-31 16:36 UTC, codingcodymiller requested changes

2022-05-31 16:36 UTC, codingcodymiller commented on object-manipulation-1/src/to-object.js
> +  for (var elementIndex = 0; elementIndex < keyValuePair.length; elementIndex++) {
This loop isn't necessary, the array will only have two indexes.

2022-06-04 15:47 UTC, Scarlet-K commented on object-manipulation-1/src/to-object.js
> +  for (var elementIndex = 0; elementIndex < keyValuePair.length; elementIndex++) {
Got it! I don't know why I was overthinking this one! Also, I was blown away by my small growth even between object-man-1 and object-man-2! Object-man-1 felt like a huge challenge just a week ago, and now looking back they are so easy!

2022-06-06 16:51 UTC, codingcodymiller approved these changes

2022-06-06 19:10 UTC, merged